---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: uv run --group dev yamllint
        language: system
        types: [yaml]
      - id: pytest
        name: pytest
        entry: uv run --group test pytest tests/
        language: system
        types: [python]
        pass_filenames: false
