---
name: Release

on:
  push:
    branches: [main]

permissions: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write # go-semantic-release creates tags and GitHub releases
    uses: projectpotos/actions/.github/workflows/semantic-release.yaml@31a073ace13fa1f689fe54cd71754f0ecba6dfb6 # v0.5.0
