---
name: Release

on:
  push:
    branches: [main]

permissions: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write # go-semantic-release creates tags and GitHub releases
    uses: projectpotos/actions/.github/workflows/semantic-release.yaml@ac5f831258705d1d8be540219f3167e208812395 # v0.4.0
